export const suggestions: string[] = [
  'Quais impactos das mudanças climáticas sobre direitos humanos na América Latina?',
  'Como eventos extremos afetam populações vulneráveis?',
  'Que obrigações legais têm os Estados frente à crise climática?',
  'Como integrar princípios de direitos humanos em políticas climáticas locais?',
  'Quais casos recentes ligam justiça climática a tribunais internacionais?',
  'Que indicadores monitoram perdas e danos em comunidades indígenas?',
  'Como secas prolongadas afetam o direito humano à água potável?',
  'De que forma inundações recorrentes comprometem o direito à moradia digna?',
  'Quais mecanismos de proteção existem para deslocados climáticos transfronteiriços?',
  'Como a mudança climática influencia padrões de migração interna no Brasil?',
  'Que salvaguardas climáticas devem ser adotadas em projetos de infraestrutura verde?',
  'Quais métricas diferenciam adaptação transformacional de adaptação incremental?',
  'Como avaliar a vulnerabilidade climática de comunidades costeiras de baixa renda?',
  'Quais direitos são acionáveis quando ondas de calor afetam a saúde ocupacional?',
  'Como incorporar gênero e interseccionalidade em planos de adaptação climática?',
  'Quais exemplos de litigância climática tiveram impacto na formulação de políticas?',
  'Como perdas e danos podem ser quantificados para reivindicações de justiça reparatória?',
  'Que princípios orientam a distribuição justa de financiamentos de transição energética?',
  'Como garantir participação pública efetiva em consultas sobre projetos de carbono?',
  'Quais riscos de greenwashing existem em créditos de carbono vinculados a direitos humanos?',
  'Como avaliar impactos de mineração de lítio sobre comunidades indígenas e clima?',
  'Que parâmetros definem deslocamento forçado versus movimentação voluntária por clima?',
  'Quais obrigações extraterritoriais Estados têm em cadeias de suprimento de energias renováveis?',
  'Como empresas podem alinhar metas Net Zero a devida diligência em direitos humanos?',
  'Quais indicadores precoces identificam insegurança alimentar causada por eventos extremos?',
  'Como traduzir cenários do IPCC em avaliações locais de risco social?',
  'Que limites éticos cercam geoengenharia solar e seus efeitos em direitos humanos?',
  'Como analisar impactos climáticos sobre o direito à educação em emergências prolongadas?',
  'Quais caminhos para integrar saberes tradicionais no monitoramento climático comunitário?',
  'Como medir resiliência social em assentamentos urbanos informais frente a eventos extremos?',
  'Quais salvaguardas legais protegem defensores ambientais ameaçados por conflitos climáticos?',
  'Como relacionar acidificação dos oceanos com segurança alimentar de comunidades pesqueiras?',
  'Quais instrumentos financeiros inovadores reduzem vulnerabilidade climática sem ampliar desigualdades?',
  'Como atribuição de eventos extremos suporta pedidos de compensação por perdas e danos?',
  'Quais metodologias transparentes estimam custo social do carbono para decisões judiciais?',
  'Como avaliar impacto de incêndios florestais em saúde mental e direitos coletivos?',
  'Quais estratégias fortalecem governança multinível para adaptação urbana justa?',
  'Como proteger povos isolados diante de expansão de fronteiras agrícolas motivadas por clima?',
  'Que abordagens de justiça intergeracional influenciam políticas climáticas de longo prazo?',
  'Como medir eficácia de sistemas de alerta precoce sob perspectiva de direitos humanos?',
  'Quais parâmetros definem energia acessível e justa na transição para renováveis?',
  'Como mecanismos REDD+ podem respeitar consentimento livre, prévio e informado?',
  'Quais riscos climáticos emergentes exigem novas categorias jurídicas de proteção?',
  'Como mapear hotspots de calor urbano e priorizar intervenções equitativas?',
  'Quais impactos da elevação do nível do mar sobre titularidade e registro de terras?',
  'Como relacionar desertificação crescente à segurança alimentar e nutricional?',
  'Quais métricas capturam vulnerabilidade diferencial de pessoas com deficiência em crises climáticas?',
  'Como aplicar o princípio de precaução em decisões sobre adaptação de infraestrutura crítica?',
  'Quais fatores de risco ligam poluição do ar urbano intensificada ao direito à saúde?',
  'Como avaliar coerência entre Contribuições Nacionalmente Determinadas e metas de direitos humanos?',
  'Quais obrigações climáticas derivam do direito internacional consuetudinário emergente?',
  'Como tribunais têm tratado nexo causal entre emissões corporativas e danos específicos?',
  'Quais caminhos para integrar indicadores de vulnerabilidade climática em políticas de proteção social?',
  'Como justiça climática dialoga com reparações históricas por colonização ambiental?',
  'Quais desafios para monitorar deslocamentos lentos causados por salinização de solos?',
  'Como frameworks de risco climático podem apoiar planejamento de saúde pública?',
  'Quais estratégias asseguram transparência em financiamento para adaptação comunitária?',
  'Como avaliar trade-offs entre conservação de biodiversidade e uso de terra para renováveis?',
  'Quais critérios definem alocação justa de fundos de perdas e danos a países vulneráveis?',
  'Como securitização da crise climática afeta garantias democráticas e liberdades civis?',
  'Quais implicações éticas surgem na priorização de realocação versus proteção costeira?',
  'Como instrumentos de seguros paramétricos podem apoiar recuperação rápida sem exclusão social?',
  'Quais metodologias comunitárias complementam dados satelitais para monitorar impactos?',
  'Como indicadores compostos de vulnerabilidade podem evitar duplicação e viés?',
  'Quais lições de casos estratégicos de litigância climática em cortes constitucionais?',
  'Como operacionalizar justiça procedimental em processos de concessão para projetos eólicos?',
  'Quais riscos emergentes para segurança hídrica urbana em cenários de aquecimento de 2°C?',
  'Como relacionar escassez hídrica a conflitos locais e proteção de direitos fundamentais?',
  'Quais abordagens de economia circular suportam mitigação sem gerar novas desigualdades?',
  'Como medir adicionalidade social em projetos de adaptação financiados internacionalmente?',
  'Quais caminhos para incorporar métricas de bem-estar climático em contas nacionais?',
  'Como ferramentas participativas digitais podem ampliar inclusão em mapeamento de riscos?',
  'Quais elementos mínimos compõem um plano municipal de adaptação centrado em direitos?',
  'Como avaliar impacto de heat islands sobre produtividade escolar e laboral?',
  'Quais indicadores antecipam riscos climáticos para cadeias de suprimento essenciais?',
  'Como direitos da criança são afetados por insegurança alimentar climática crônica?',
  'Quais oportunidades de co-benefícios entre redução de emissões e equidade em mobilidade?',
  'Como cidades podem integrar princípios de justiça climática em zoneamento urbano?',
  'Quais lacunas de dados dificultam monitorar impactos climáticos em populações rurais dispersas?',
  'Como incluir métricas de saúde mental em avaliações de perdas e danos?',
  'Quais estratégias aceleram transição justa para trabalhadores de setores fósseis?',
  'Como métricas de risco composto podem priorizar investimentos resilientes?',
  'Quais papéis do setor financeiro na prevenção de riscos climáticos a direitos humanos?',
  'Como diferenciar adaptação baseada em ecossistemas de soluções com greenwashing?',
  'Quais instrumentos jurídicos suportam reconhecimento de deslocados climáticos internacionais?',
  'Como mensurar responsabilidade corporativa por cadeias de valor emissoras intensivas?',
  'Quais desafios éticos cercam uso de big data ambiental em governança climática?',
  'Como modelos de previsão podem ser comunicados sem gerar alarmismo ou apatia?',
  'Quais ações de mitigação geram maior co-benefício sanitário em curto prazo?'
];